### ISSUE TITLE
Problem with packages

### ISSUE THREAD

**Issue by bluebay** [meteor/windows-preview#101]
With the latest version of windows preview, i.e., 0.3.0, I am unable to install some packages.
When trying to install some packages, I get No compatible build found.

For example: Please refer to this issue: https://github.com/CollectionFS/Meteor-CollectionFS/issues/607

I guess this problem is because of the meteor version mentioned in the release file.

**Comment by ganySA** [comment]
Hi

Please see the solution i posted in #127 for a temp fix for this. I have collectionFS working. Until they start compiling builds specifically for windows this will affect many packages.

Cheers

**Comment by stubailo** [comment]
@bluebay please file issues on packages that are not built for Windows. Here is a link that you can give them with directions on how to republish: https://github.com/meteor/meteor/wiki/Publishing-a-package-with-binary-dependencies-for-the-Windows-preview

Thanks for reporting! Going to close the issue here, it's up to the individual package authors now.

**Comment by bluebay** [comment]
@stubailo Thanks.
