### ISSUE TITLE
Packages with binaries

### ISSUE THREAD

**Issue by fredrikekelund** [meteor/windows-preview#45]
Half question, half issue here. What's the plan for the Meteor packages that contain binary code and pre-compiled bundles for the Windows platform?

Whatever the eventual solution (I know you've mentioned moving onto automated compilation of packages at some point), maybe it could be nice to try and compile the package on the client if the current platform is Windows and no supported build of the package is available? That would help everyone trying to run the SASS compiler and whatnot

**Comment by stubailo** [comment]
Our current plan is that it will be the same system as for Linux and Mac - you run `meteor admin get-machine os.windows.x86_32` and then run `publish-for-arch`. We might also explore some options for automatically compiling existing packages.

**Comment by aldeed** [comment]
@stubailo, is there an ETA for when `meteor admin get-machine os.windows.x86_32` command will work? I've had a couple requests to publish binary packages for Windows. Is there an interim way? Can we use the Windows preview and `publish-for-arch` locally on a Windows machine? I have not tried the Windows preview yet.

**Comment by stubailo** [comment]
`meteor --release WINDOWS-PREVIEW@0.1.8 admin get-machine os.windows.x86_32` works for me. Keep in mind that there is a weird thing where the screen doesn't clear when SSH starts, so the prompt will appear at the top over your existing terminal text.

**Comment by aldeed** [comment]
@stubailo I am able to get the machine but when trying to `publish-for-arch`, I always get

```
Sorry, Meteor 1.0.1 is not installed and could not be                         
downloaded. Please check to make sure that you are online. 
```

These were the commands I tried:

```
$ meteor publish-for-arch cfs:gridfs@0.0.26
$ meteor publish-for-arch cfs:gridfs@0.0.27
```

I'm not sure why it's looking for Meteor 1.0.1 in particular, but regardless I would think the build machines should be able to download missing Meteor versions. Unless it's because there was no windows preview for that version.

**Comment by stubailo** [comment]
Ah - the problem is that you published the package from a version of Meteor that doesn't exist on Windows.

We aren't going to try to match Windows releases to old versions of Meteor - when Meteor 1.1.0 comes out it will support Windows but no previous versions will.

You can keep your current `api.versionsFrom` call inside `package.js`, and then publish your package using `WINDOWS-PREVIEW@0.1.8` on all platforms, and everything should be fine.

**Comment by aldeed** [comment]
@stubailo, unfortunately still can't quite get this to work.

I bumped the patch version and published using the preview (on OSX):

```
$ meteor publish --release WINDOWS-PREVIEW@0.1.8
```

Which succeeded. BTW, it gave me a message starting with "You can access Meteor provided build machines, pre-configured to support older..." which listed the available build machines and did NOT list the windows one, so you should add the windows command to that list.

Anyway, then I did `meteor --release WINDOWS-PREVIEW@0.1.8 admin get-machine os.windows.x86_32`.

Which worked, but then this:

```
C:\Windows\system32>meteor publish-for-arch cfs:gridfs@0.0.28
This package has no valid version lock file: are you trying to use publish-for-a
rch on                                                                          
a core package? Publish-for-arch cannot guarantee safety. Please use
publish --existing-version instead.  
```

Also tried with release:

```
C:\Windows\system32>meteor --release WINDOWS-PREVIEW@0.1.8 publish-for-arch cfs:
gridfs@0.0.28
```

But then the error was `--release should only be passed once.`

I appreciate any insight.

**Comment by stubailo** [comment]
Interesting, I will try this myself!

**Comment by fourseven** [comment]
I'm getting the same. Tried `meteor --release WINDOWS-PREVIEW@0.1.8 publish` my package `fourseven:scss@2.0.1` (on a Mac) which broke the package for the isopack build machines (with a `Malformed source tarball` error). 

Should I be able to use the windows release on a mac?

Did another release `fourseven:scss@2.0.1_2` back on meteor `1.0.3.2` which then spat 

```sh
C:\Windows\system32>  meteor publish-for-arch fourseven:scss@2.0.1_1
This package has no valid version lock file: are you trying to use publish-for-a
rch on
a core package? Publish-for-arch cannot guarantee safety. Please use
publish --existing-version instead.
```

When trying to publish on the windows build box. Linux and OS X built that version fine.

**Comment by avital** [comment]
@fourseven Since I see that `fourseven:scss` has been [published for Windows](https://github.com/fourseven/meteor-scss/issues/78), I'll assume this issue is resolved.

If there are any other issues about building packages for Windows, please file them in   the [meteor/meteor](https://github.com/meteor/meteor) repository. This repository will be closed soon.
