### ISSUE TITLE
Normalizing file paths for build plugins

### ISSUE THREAD

**Issue by fredrikekelund** [meteor/windows-preview#47]
I encountered an issue when using Urigo:angular-meteor with the windows preview. That package uses a build plugin to compile angular templates and store every template in an object, where the key is the path to the file as passed to the build plugin by Meteor.

A problem arises when the file path is inconsistent between platforms, because when running on *nix the templates are effectively stored as client/template/foo.bar and on windows they're stored as client\template\foo.bar.

This could of course be made an issue for the plugin developers to deal with, but I wanted to raise a question nonetheless about whether the file paths should be normalized across platforms somehow?

**Comment by stubailo** [comment]
This is a very important question! Actually internally to the framework we currently convert all paths to normalized Unix-style paths. We intentionally convert them back to the system-style paths when passing to build plugins right now.

A big part of the reason is that otherwise native FS functions won't work - `path.join`, for example, only knows how to work with Windows paths on Windows and Unix paths on Unix. If we always passed unix-style paths to build plugins, we would probably have to provide a whole library to replace `fs` and `path` to deal with the path discrepancies.

We figured it was more consistent with what people expect to give them the real paths from the files system, and they can decide how to handle them in their plugin. I'd like to open up a conversation around it, though - what would plugin developers prefer? @Urigo

**Comment by Urigo** [comment]
@fredrikekelund
So what we do in angular-meteor is that we load templates to the cache using Angular's $templateCache.
$templateCache can take any name you want but we put in the name as the path with

    compileStep.inputPath

to make it easier for the developers to pull those in like it was a regular file.

    compileStep.inputPath.toPlatform()

 @stubailo ,Does it sound reasonable?

**Comment by stubailo** [comment]
Another option would be like `compileStep.fileSystemPath` and `compileStem.displayPath`?

**Comment by Urigo** [comment]
yes that's great

**Comment by stubailo** [comment]
Going to close this, if you still need this feature file an issue on meteor/meteor
