### ISSUE TITLE
Windows Firewall has blocked some features of this app

### ISSUE THREAD

**Issue by KyleMit** [meteor/windows-preview#61]
When running meteor from a new directory I get the following alert:

![screenshot][1]

>Windows firewall has blocked some features of Evented I/O for V8 JavaScript on all public and private networks
    **Name**: Evented I/O for V8 for Javascript
    **Publisher**: Joyent, Inc
    **Path**: %LocalAppData%\.meteor\packages\meteor-tool\1.1.0-winr.7\mt-os.windows.x86_32\dev_bundle\bin

Of course, I can just click <kbd>Allow Access</kbd> and it works just fine, but it would be nice to have an instruction on what to change in the Windows Firewall settings for a permanent solution.

It could be added to the [Windows Guide][2] or just live here.

[1]: http://i.imgur.com/toTp4fR.png
[2]: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by stubailo** [comment]
This happens whenever you run a new version of Meteor, since we download a new Node executable for each version.

It would compromise your computer's security to have these warnings not pop up - the best you could do would be to allow all executables called "node.exe" through the firewall, but then any spyware could call itself node.exe and be let through.

**Comment by stubailo** [comment]
A good improvement would be to avoid downloading unnecessary new node executables. @Slava what do you think?

**Comment by Slava** [comment]
I don't think we can avoid downloading new execs easily. I also don't know how Windows differentiates the binaries.

**Comment by stubailo** [comment]
Maybe the actual file path, or some signature?

**Comment by sdarnell** [comment]
Windows firewall exclusions are usually on the full path name (not signature). But remember that there are quite a few different firewalls out there.

Probably the best option would be to arrange for each node version to be stored in a node specific directory rather than a tools specific area.
Maybe arrange a check and copy when a given tools version of executed.

Having said that, I've done more than my fair share of meteor installations, and although it is a minor irritation I suspect it is one that most people can understand and live with.

Also the numbers of releases will inevitably slow down a bit... maybe ... ;-)

**Comment by Slava** [comment]
I share Stephen's prediction on low number of node updates and bearability of these popups.
