### ISSUE TITLE
Meteor version command : 

### ISSUE THREAD

**Issue by indcoder** [meteor/windows-preview#68]
When running the command meteor --version I should be getting the version of Meteor being used....not the version of Windows Meteor installer. [Feb 9th installer]
![screenshot 2015-02-13 21 25 12](https://cloud.githubusercontent.com/assets/2099300/6190324/13958ba6-b3c7-11e4-8c22-a51ca27e96a4.png)

**Comment by stubailo** [comment]
Hi @indcoder, this is a result of the version number hacking we have to do to stop Meteor on Windows from trying to download `METEOR@1.0.3.1` whenever you run it. Right now, it thinks that the release track `WINDOWS-PREVIEW` is the official main one, so instead of printing `WINDOWS-PREVIEW@0.1.7` it prints `Meteor 0.1.7`.

In short, this won't be a problem once we switch from the `WINDOWS-PREVIEW` release track to the official one.
