### ISSUE TITLE
Must press Ctrl+C twice, and get "Terminate batch job (Y/N)?" multiple times

### ISSUE THREAD

**Issue by dandv** [meteor/windows-preview#73]
![meteor windows cmd ctrl c twice terminate y](https://cloud.githubusercontent.com/assets/33569/6257053/f3ff1326-b771-11e4-91c0-09bc9c660bc0.png)

To reproduce, just Ctrl+C any running Meteor app.

Another example:

```
c:\prg\met\webix-meteor-example>meteor run --port 3030
[[[[[ c:\prg\met\webix-meteor-example ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3030/
Terminate batch job (Y/N)? Terminate batch job (Y/N)? y

c:\prg\met\webix-meteor-example>
Terminate batch job (Y/N)? y
'y' is not recognized as an internal or external command,
operable program or batch file.

c:\prg\met\webix-meteor-example>
Terminate batch job (Y/N)? y
'y' is not recognized as an internal or external command,
operable program or batch file.

c:\prg\met\webix-meteor-example>
Terminate batch job (Y/N)?
c:\prg\met\webix-meteor-example>
Terminate batch job (Y/N)?
c:\prg\met\webix-meteor-example>
Terminate batch job (Y/N)? y
'y' is not recognized as an internal or external command,
operable program or batch file.

c:\prg\met\webix-meteor-example>
Terminate batch job (Y/N)?
^C
C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\bin\node.exe was unexpected at this time.

c:\prg\met\webix-meteor-example>
```

`meteor --version`: `Meteor 0.1.7`

**Comment by Slava** [comment]
Well, that's how batch scripts in Windows work. And so are vbs, jscript, ps1 and other scripts work.

We could potentially build a binary to run `meteor` but right now it is too risky, given that we are not familiar with building and distributing binaries working on all windows machines no matter what frameworks or sdks you have installed (I guess we could link only against libc and stdlibc). @stubailo and I already tried that and it worked and we might do that at some point in the future.

But so far you need to press `C-c` twice, just like you do for `npm`, for example.

**Comment by dandv** [comment]
That is strange, because if I remember correctly, until a few versions ago, I only had to press Ctrl+C once, and the prompt didn't reappear when typing something after the first Ctrl+C.

Is it possible that an older version of the Windows preview had a better interrupt handling mechanism?

**Comment by Slava** [comment]
All versions released by MDG worked this way (pressing C-c twice)

**Comment by dandv** [comment]
Correct. Pressing Ctrl+C twice works. I think it was the case that pressing Ctrl+C then `y` worked as well, but I don't think it's worth investigating why it no longer works. The only problem is that users might not know about the double Ctrl+C trick, and when they see the prompt `Terminate batch job (Y/N)?`, they'll press `y` many times until finally pressing Ctrl+C a second time.

**Comment by smeijer** [comment]
I don't think developers are "normal" users, that don't understand how to press `ctrl+c`. I can see why it doesn't make sense to linux-devs, but I think windows-devs are common with it. Perhaps a subtle hint in the start-up log will help the unknowing, but I wouldn't spend time on changing the behavior. There are more important things to spend time on.

What I meant with the start-up log, is something like:

```txt
=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
press ctrl+c (twice) to exit
_
```

**Comment by sdarnell** [comment]
Sadly there isn't a way of persuading batch files not to do this. Other than patching cmd.exe which is clearly not on.

The solution is to create a simple c/c++ wrapper, which could even have libraries statically linked (though even that probably isn't necessary).  In my port I reused the LaunchMeteor.exe which was. Net based for convenience, and because it needed access to certain libraries - but with the new installer that shouldn't be an issue.

The other problem with bat files is that various versions of bash etc refuse to run them. So I think the exe wrapper is unfortunately needed.

**Comment by Slava** [comment]
There are reasons why a separate exe binary is not easy to implement at this stage of our development.

- the `meteor.bat` file that can be found in your PATH env variable is actually calling another `meteor.bat` file somewhere deep inside of Meteor installation. The logic that generates this file is complicated and is used extensively on unix environments (via bash scripts and symlinks).
- the main executable file, `meteor.exe` or `meteor.bat` is read by the updater in Meteor tool to figure out, what is the latest installed version of meteor. On unix, it wasn't weird, since the main `meteor` executable was just a symlink to the real bash script, we could just read the contents of the symlink. On Windows we have chains of bat files, the main one containing a comment with the full version it is going to run.

We can spend another week trying to rewrite this logic on unix and windows, or we can release the batch script version and see how people use it.

**Comment by stubailo** [comment]
I added a message that says to type control-c twice.

**Comment by ttamminen** [comment]
What we did to prevent double Ctrl + C was to wrap execution to a shell script. We support multiple development operating systems and everything has gone smoothly. I wrote a blog post about the problem and solution, hopefully it gives some ideas: http://triplet.fi/blog/getting_rid_of_terminate_batch_job_while_developing_node_application_on_windows/
