### ISSUE TITLE
Need Reset Meteor because MongoDB

### ISSUE THREAD

**Issue by engenheiro** [meteor/windows-preview#81]
Sometimes MongoDB return error on app start. The "solution" is "meteor reset". Why?

**Comment by Slava** [comment]
This happens when MongoDB is not killed properly. MongoDB would leave a lock file indicating that an instance running previously didn't clean up after itself. `meteor reset` removes the local database completely, even if the solution was just to delete `mongodb.lock` file. If you start with a clean new database, everything would just work.

The problem of killing mongodb properly was fixed on `devel` branch. We are tracking other cases of MongoDB misbehaving in #8.
